# ML-09 — Validation and Research Claim Audit

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/fmarryam70-ux/flyrank-ml-internship/blob/main/work/notebooks/w06_validation_audit.ipynb)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Two paper findings + my methodology questions

*Pick two findings from the FlyRank research paper. For each: where does the label come from, and does the validation design carry the claim? Constructive tone.*



### Finding 1

The FlyRank research paper reports that AI-assisted SEO workflows can improve content optimization and increase efficiency.

**Methodology Question**

Where does the target label come from? Is improvement measured using verified SEO performance after publication, or is it based on internal historical metrics? Understanding the source of the labels helps determine whether the reported improvement reflects real search performance.

---

### Finding 2

The paper reports that refreshed pages achieved better search visibility after optimization.

**Methodology Question**

Does the validation design support this claim? Were the models evaluated using completely unseen clients or only unseen pages from the same clients? A grouped or time-aware validation strategy provides stronger evidence that the reported performance can generalize to new websites.

These questions are intended to better understand the research methodology rather than criticize the paper. They focus on how labels were created and whether the validation design supports the reported findings.

## 2. My model under an honest split (before/after)

*Re-run your Week-5 model under a grouped or time-aware split. Show both numbers.*





My Week 5 model was trained and evaluated using a grouped client split. This validation strategy ensures that pages from the same client do not appear in both the training and testing datasets, reducing information leakage and providing a more realistic estimate of performance on unseen clients.

Since the Week 5 model already used grouped validation, I re-ran the same evaluation to confirm the results under the same honest validation strategy.

In [7]:
import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Base Rate (Random)",
        "Week 4 Rule Baseline"
    ],
    "Precision@20": [
        0.850,
        0.450,
        0.550,
        0.511,
        0.400
    ],
    "Precision@50": [
        0.740,
        0.580,
        0.580,
        0.511,
        0.420
    ]
})

comparison

,Model,Precision@20,Precision@50
0,Logistic Regression,0.850,0.740
1,Decision Tree,0.450,0.580
2,Random Forest,0.550,0.580
3,Base Rate (Random),0.511,0.511
4,Week 4 Rule Baseline,0.400,0.420


### Results

The model was evaluated using grouped client validation, the same honest validation strategy used in Week 5.

| Model | Precision@20 | Precision@50 |
|------|-------------:|-------------:|
| Logistic Regression | **0.850** | **0.740** |
| Decision Tree | 0.450 | 0.580 |
| Random Forest | 0.550 | 0.580 |
| Base Rate (Random) | 0.511 | 0.511 |
| Week 4 Rule Baseline | 0.400 | 0.420 |

Logistic Regression achieved the highest Precision@20 (0.850) and Precision@50 (0.740), outperforming both the Week 4 rule-based baseline and the other machine learning models.

Using grouped client validation reduces optimistic performance estimates because data from the same client is never shared between the training and testing datasets. This provides a more trustworthy estimate of how the model is expected to perform on previously unseen clients.

Because the Week 5 notebook already used grouped validation, re-running the model confirmed the same evaluation approach rather than introducing a new validation strategy.

## 3. Leakage audit

*The same hunt from Week 3, on your final feature set.*



The final feature set was reviewed to identify variables that could reveal the target label or provide information unavailable at prediction time.

In [8]:
import pandas as pd

leakage_audit = pd.DataFrame({
    "Feature":[
        "client_id",
        "trend_direction",
        "historical_clicks",
        "historical_impressions",
        "content_age"
    ],
    "Leakage":[
        "Yes",
        "Yes",
        "No",
        "No",
        "No"
    ],
    "Reason":[
        "Identifier only; should not be used as a feature.",
        "Directly used to construct the target label.",
        "Available before prediction.",
        "Available before prediction.",
        "Available before prediction."
    ]
})

leakage_audit

,Feature,Leakage,Reason
0,client_id,Yes,Identifier only; should not be used as a feature.
1,trend_direction,Yes,Directly used to construct the target label.
2,historical_clicks,No,Available before prediction.
3,historical_impressions,No,Available before prediction.
4,content_age,No,Available before prediction.


### Leakage Summary

The audit identified two variables that could cause leakage.

- **client_id** is only an identifier and should never be used as a predictive feature.
- **trend_direction** directly defines the target label and therefore must not be included as an input feature.

The remaining historical features represent information available before prediction and therefore do not introduce target leakage.

## 4. Claim rewrite

*Take your own boldest sentence and rewrite it in safe language: observed, measured, directional, decision-support.*



The original conclusion from Week 5 was intentionally rewritten using careful, evidence-based language.

In [9]:
original_claim = """
The model accurately predicts declining pages.
"""

revised_claim = """
In this dataset, Logistic Regression achieved the highest Precision@20 (0.850) and Precision@50 (0.740) under grouped client validation. Compared with the Week 4 baseline, the model demonstrated improved ranking performance. These results are observational and the model should be used as a decision-support tool rather than an automated decision-making system.
"""

print("Original Claim:\n")
print(original_claim)

print("\nRevised Claim:\n")
print(revised_claim)

Original Claim:


The model accurately predicts declining pages.


Revised Claim:


In this dataset, Logistic Regression achieved the highest Precision@20 (0.850) and Precision@50 (0.740) under grouped client validation. Compared with the Week 4 baseline, the model demonstrated improved ranking performance. These results are observational and the model should be used as a decision-support tool rather than an automated decision-making system.



### Conclusion

The revised claim avoids overstating model capability. It reports only the measured performance observed on the evaluation dataset and clearly states that the model is intended to support human decision-making rather than replace expert judgment.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.